language: c

os:
  - linux
  - osx

env:
  global:
    - GIT_DESCRIBE_NUMBER=$TRAVIS_BUILD_NUMBER
    - GIT_BUILD_STR=$TRAVIS_COMMIT
  matrix:
    - PYTHON_TARGET=3.5
    - PYTHON_TARGET=3.6

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      rvm get stable --auto-dotfiles;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels estnltk
  - conda config --add channels conda-forge
  # Useful for debugging any issues with conda
  - conda info -a
  
  # Install build tools
  - conda install conda-build anaconda-client swig cython
  - conda update conda-build
  - anaconda login --hostname "$TRAVIS_BUILD_NUMBER"_"$PYTHON_TARGET" --username estnltk --password "$ESTNLTK_ANACONDA_PASSWORD"

script:
  # Build estnltk
  - filename=`conda build --py $PYTHON_TARGET conda-recipe --output`
  - echo "Building" $filename
  - conda build --py $PYTHON_TARGET conda-recipe
  - ls -lah `$filename`
  - anaconda upload -l dev $filename
