language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"

install:
  - sudo apt-get update
  - sudo apt-get -y remove swig
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels stacc
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda install conda-build
  - conda create -q  -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda build conda-recipe
  - conda install estnltk --use-local

script:
  #test script
